---
title: Code Repositories
author: Thomas Goossens
date: '2017-04-01'
---

## Agromet project

* [agrometAPI](https://github.com/pokyah/agrometAPI)
R package to play with the Agromet API

* [agrometInternship](https://github.com/pokyah/agrometInternship)
Repository containing the reports from or interns. These reports are written with [thesisdown](https://github.com/ismayc/thesisdown) package. A report = a specific branch

* [mlr](https://github.com/pokyah/mlr)
My ongoing contribution to the machine learning [mlr R](https://mlr-org.github.io) package. This contributions aims to integrate the famous geostatistical modelling [gstat package](https://cran.r-project.org/web/packages/gstat/gstat.pdf) into mlr.

* [defHydWal](https://github.com/pokyah/defHydWal)
A simple shiny app coded as a package to explore the water deficit in Wallonia. This was integrated to a shiny server as explained in my [post](https://pokyah.github.io/post/2018-08-01-building-a-dockerized-shiny-server-with-packaged-shiny-apps/)

* [Public Agromet code](https://github.com/pokyah/agrometeor-public)  
Working tested code related to the Agromet project and sufficiently documented.

* [AgrometeoR Docker](https://github.com/pokyah/agrometeorDocker)  
Dockerfile for AgrometeoR development environment using Docker based on rocker R studio container

* [geoTools](https://github.com/pokyah/geoTools)
An R package aimed to prepare geospatial data that is required for our weather spatialization (DEM, Corine Land Cover, admin borders, etc...)

* [AgrometeoR Spatial Benchmarking](https://github.com/pokyah/agrometeor-spatial-benchmarking)
Benchmark of various machine learning regression methods

* [AWS Humain Comparison](https://github.com/pokyah/AWS-Humain-comparison)
Comparing measurements from 2 types of automatic weather stations

* [Spatialization Review and Benchmarking](https://pokyah.github.io/agrometeor-spatialization-review-benchmark/)
A review of weather spatialization methods

* [Spatialization methodology](https://pokyah.github.io/agrometeor-methodo-spatial/)
Presentation about Agromet Spatialization methodo

## Other projects

* [my personal blog](https://pokyah.github.io)  
Where I post my tutorials related to openGIS, data-analysis and Linux stuffs

* [R utilities](https://pokyah.github.io/R-utilities/)
Global R utility functions

* [R project initializer](https://github.com/pokyah/R-project-init)
Create a tree + .gitignore + git init + LICENSE + REDAME.md for your new R project with a single bash command

* [CRA-W revealjs template](https://github.com/pokyah/craw-reveal-template)  
CSS template for authoring revealjs presentations with the CRA-W graphic chart.

# Useful books

* [Geocomputation with R](http://geocompr.robinlovelace.net/)  
Publicly available and with an excellent chapter about spatial cross-validation.

* [Efficient R Programming](https://csgillespie.github.io/efficientR/)
Worth reading to improve your R skills and workflows for a better productivity

* [Happy git with R](http://happygitwithr.com/big-picture.html)
Work efficiently with R + git combo

* [An Intro to R](https://colinfay.me/intro-to-r/)
The basics !

# Data-analasys packages

* [mlr with R](https://mlr-org.github.io/mlr/)  
"umbrella" package for machine learning (Machine learning, more specifically the field of predictive modeling is primarily concerned with minimizing the error of a model or making the most accurate predictions possible, at the expense of explainability)

* [mlr benchmark vis](https://github.com/collinleiber/benchmarkVis)
Benchmark Visualizations in R

